### ISSUE TITLE
Cannot format due to syntax errors

### ISSUE THREAD

**Issue by Binero** [saviorisdead/RustyCode#119]
When running `>Format` in a rust file, VSC always gives me `Cannot format due to syntax errors`. I have my rustfmt path configured correctly. I set it to `/home/myusername/.cargo/bin/rustfmt`. 

How to fix?

**Comment by JohanSJA** [comment]
Most of the time, I am getting this when my source code has some invalid syntax. It will run fine once I corrected the source code.

Maybe refer to this:
- https://github.com/rust-lang-nursery/rustfmt (`Running` section)
- https://github.com/saviorisdead/RustyCode/blob/master/src/services/formatService.ts#L101

Perhaps we can do is returning more useful error. Not sure how that would be done though.

**Comment by Binero** [comment]
My code does not have any errors as it compiles fine. Running `rustfmt` manually outside VSC also works flawlessly.

**Comment by conikeec** [comment]
I am still encountering the same issue and filed two requests with no resolution recommended.

Refer : https://github.com/saviorisdead/RustyCode/issues/112

**Comment by LaurentTreguier** [comment]
I'm having the exact same issue with VSCode 1.1.0, RustyCode 0.14.3 and rustfmt 0.5.0. Even a simple Hello world program produces the warning.

**Comment by conikeec** [comment]
@saviorisdead just put a fix. Refer https://github.com/saviorisdead/RustyCode/issues/112
@Binero please upgrade.
Works like a charm

**Comment by LaurentTreguier** [comment]
Though it did some weird bracket duplicating at first, probably after restarting VSCode I can confirm it now works perfectly.

**Comment by irobert91** [comment]
I'm still having this issue in VSCode 1.2.1 with Rusty Code 0.14.6 on Ubuntu 14.04
