### ISSUE TITLE
rustfmt 0.6.0 seems broken

### ISSUE THREAD

**Issue by CryZe** [saviorisdead/RustyCode#164]
I just updated my rustfmt to 0.6.0 and now RustyCode always says `Cannot format due to syntax errors`, which is weird, cause manually invoking `cargo fmt` works just fine without any warnings. It might just be me, but it used to work before, so it's kind of weird that it doesn't now.

**Comment by trixnz** [comment]
This is fixed by https://github.com/saviorisdead/RustyCode/pull/161

**Comment by CryZe** [comment]
Oh, totally missed that. Thanks for the fix :D

**Comment by kdar** [comment]
It seems to me like #161 does not fix rustfmt 0.6.0. Looking at the output of rustfmt's diff, it seems to have changed. 

https://github.com/rust-lang-nursery/rustfmt/commit/a0de408198d5f1e8e2d96b471450af3742dfdddc#diff-4867ec103faeb4d5bb7651bcdb33994a

**Comment by trixnz** [comment]
@kdar good catch, at the time I wrote the PR the version of master I was on didn't have the changed output. I suppose we're going to need to write in a backwards compatibility layer too 😞. I'll add it to my todo list.

**Comment by physhh** [comment]
If you are looking for a solution to this now, here is a patch which works with rustfmt 0.6.0:
https://gist.github.com/physhh/e686d1ef3d43ff15b0073a0f888e9fc2

Relevant code of rustfmt:
https://github.com/rust-lang-nursery/rustfmt/blob/e1759ae295a65b28636d4635f76daa129eed9be0/src/filemap.rs#L151 
https://github.com/rust-lang-nursery/rustfmt/blob/35624c54e5d7db6db232a2c814441473acc37cfd/src/rustfmt_diff.rs#L118

Patch does not care about backward compatibility to older rustfmt versions.

**Comment by kdar** [comment]
Awesome! Thank you @physhh

**Comment by trixnz** [comment]
This is fixed with backwards compatibility in #173 👍

**Comment by W4RH4WK** [comment]
Anything left to do here?

**Comment by CryZe** [comment]
Nope, it seems to work perfectly :)

2016-10-23 20:03 GMT+02:00 Alex Hirsch <notifications@github.com>:
